[General]
configversion=6.1
firstlaunch=true
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0\0\0\0\0\0\0\0\t\xff\0\0\x5\x83\0\0\0\xac\0\0\0\xd4\0\0\x1\xd3\0\0\x1\xfb\0\0\0\0\x2\0\0\0\n\0\0\0\0\0\0\0\0\0\0\0\t\xff\0\0\x5\x83)
optionsgeometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\x3\xe8\0\0\x1{\0\0\x5\xd8\0\0\x3\xa8\0\0\x3\xe8\0\0\x1{\0\0\x5\xd8\0\0\x3\xa8\0\0\0\0\x2\0\0\0\n\0\0\0\x3\xe8\0\0\x1{\0\0\x5\xd8\0\0\x3\xa8)
optionstab=1

[options]
afterdelete=2
allowmimecontentdetection=false
askdelete=true
bgcolor=#212121
bgcolorenabled=true
colorspaceconversion=1
cropmode=0
cursorzoom=true
filteringenabled=false
fullscreendetails=false
language=system
loopfoldersenabled=true
maxwindowresizedpercentage=70
menubarenabled=false
minwindowresizedpercentage=20
pastactualsizeenabled=true
preloadingmode=1
quitonlastwindow=false
saverecents=true
scalefactor=25
scalingenabled=true
scalingtwoenabled=false
scrollzoomsenabled=true
slideshowreversed=0
slideshowtimer=5
sortdescending=0
sortmode=0
titlebaralwaysdark=true
titlebarmode=1
updatenotifications=false
windowresizemode=1

[shortcuts]
copy=Ctrl+C, Ctrl+Ins, F16
decreasespeed=[
delete=Ctrl+Backspace, Del, Ctrl+D
firstfile=Home
flip=Ctrl+F
fullscreen=@Invalid()
increasespeed=]
lastfile=End
mirror=F
nextfile=Right
nextframe=N
open=Ctrl+O
opencontainingfolder=@Invalid()
openurl=Ctrl+Shift+O
options=@Invalid()
originalsize=O
paste=Ctrl+V, Ctrl+Shift+Ins, Shift+Ins, F18
pause=P
previousfile=Left
quit=Ctrl+Q, Ctrl+W
rename=Ctrl+Return, F2, Ctrl+R
resetspeed=\\
resetzoom=Ctrl+0
rotateleft=Down
rotateright=Up
saveframeas=Ctrl+S
showfileinfo=I
slideshow=@Invalid()
undo=Ctrl+Z, F14
zoomin=Ctrl++, "Ctrl+="
zoomout=Ctrl+-
